task_manager/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from tasks.views import CreateUser

urlpatterns = [
	url(r'^login/$', auth_views.login, {'template_name': 'tasks/login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'template_name': 'tasks/logout.html'}, name='logout'),
    url(r'^new-user/$', CreateUser.as_view(), name='create_user'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('tasks.urls')),
]

tasks/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.task_list, name='main'),
    url(r'^task/(?P<pk>\d+)/edit/$', views.task_edit, name='task_edit'),
    url(r'^delete/(?P<pk>\d+)/$', views.DeleteTask.as_view(),
        name='task_delete',),
    url(r'^complete/(?P<pk>\d+)/$', views.task_complete, name='task_complete'),
    url(r'^add/$', views.AddTask.as_view(), name='task_add'),
]

tasks/models.py
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User

class Task(models.Model):

	number = models.IntegerField(null=True)
	title = models.CharField(max_length=20)
	text = models.TextField(blank=True)
	user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
	completed = models.NullBooleanField(null=True)
	date_created = models.DateField(blank=True, null=True)
	date_completed = models.DateField(blank=True, null=True)

	def __str__(self):
		return self.title

tasks/forms.py
from django import forms
from .models import Task

class TaskForm(forms.ModelForm):

    class Meta:
        model = Task
        fields = ('title', 'text','user')

tasks/views.py
from .models import Task, User
from .forms import TaskForm
from django.shortcuts import redirect, render, get_object_or_404
from django.views.generic.edit import CreateView, DeleteView
from django.core.urlresolvers import reverse, reverse_lazy
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm

def task_list(request):
	if request.user.id:
		user = request.user.id
		tasks = Task.objects.filter(user=user)
	else:
		tasks = Task.objects.all()
	return render(request, 'tasks/main.html', {'tasks': tasks})

def task_edit(request, pk):
	task = get_object_or_404(Task, pk=pk)
	if request.method == "POST" and request.POST.get('delete'):
		task.delete()
		return redirect('main') 
	if request.method == "POST":
		form = TaskForm(request.POST, instance=task)
		if form.is_valid():
			task = form.save(commit=False)
			task.save()
			return redirect('main')
	else:
		form = TaskForm(instance=task)
	return render(request, 'tasks/edit.html', {'task': task})

def task_complete (request, pk):
	completed_task = Task.objects.get(pk=pk)
	completed_task.completed = True 
	completed_task.save()
	tasks = Task.objects.all()
	return render(request, 'tasks/main.html', {'tasks': tasks})


#This way of implementing delete is modular, brief, and keeps us safe from CSRF attacks.
class DeleteTask(DeleteView):
    model = Task
    template_name = 'tasks/delete_task.html'
    success_url = reverse_lazy('main')

    def get_sucess_url(self):
    	return success_url


class AddTask(CreateView):
	form_class = TaskForm
	template_name = 'tasks/add_task.html'
	success_url = reverse_lazy('main')

	#def task_valid(self, form):
	#	task_ = Task.objects.create()
	#	form.save(for_task=task_)

class CreateUser(CreateView):
	form_class = UserCreationForm
	template_name = 'tasks/create_user.html'

	def get_success_url(self):
		return reverse('main')

tasks/templates/tasks/add_task.html
{% extends "tasks/base.html" %}
{% block content %}

<h1>Add a new task</h1>

<form action="{% url 'task_add' %}" method="POST">{% csrf_token %}
	{{ form.as_p }}
	<input type="submit" value="Save" />
	<a href="{% url "main" %}">No, cancel.</a>
</form>

{% endblock %}

tasks/templates/tasks/base.html
<html>
<head>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
</head>
<body>

{% load breadcrumbs %}

{% block breadcrumbs %}
{% breadcrumb_url 'main' 'main' %}
{% endblock %}
  
<div>
    Hello! Welcome to Tai's Blog! This page is a web app that's meant to function as a
    online taskmanager. This is an example to demonstrate my django skills. Right now you
    are seeing all tasks, log in to only see yours. Log in to only see tasks belonging to a specific user. 
    {% if not user.is_authenticated %}
    	<a href="{% url 'login' %}">Click here to log in</a>
    {% else %}
    You are logged in. <a href="{% url 'logout' %}">Click here to logout.</a>
    {% endif %}
</div>

{% block content %}
{% endblock %}

</body>
</html>

tasks/templates/tasks/create_user.html
{% extends "tasks/base.html" %}

{% block content %}
<h1>Create New User</h1>
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Create Account">
</form>
{% endblock %}

tasks/templates/tasks/delete_task.html
{% extends "tasks/base.html" %}
{% block content %}

<h1>Delete Task</h1>

<p>Are you sure you want to delete the task {{ task }}?</p>

<form action="{% url "task_delete" pk=task.pk %}" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete." />
  <a href="{% url "main" %}">No, cancel.</a>
</form>

{% endblock %}

tasks/templates/tasks/edit.html
{% extends 'tasks/base.html' %}

{% block content %}
<h1>Edit Task</h1>
<form method="POST" class="post-form">{% csrf_token %}
         <p><label for="id_title">Title:</label> <input id="id_title" maxlength="20" name="title" type="text" /></p><p><label for="id_text">Text:</label> <textarea cols="40" id="id_text" name="text" rows="10"></textarea></p><p><label for="id_user">User:</label> <input id="id_user" maxlength="20" name="user" type="text" /></p>
        <button type="submit" class="save btn btn-default">Save</button>
</form>

{% endblock %}

tasks/templates/tasks/login.html
{% extends "tasks/base.html" %}

{% block title %}Login{% endblock %}

{% block content %}
  <h2>Login</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
  </form>
{% endblock %}

tasks/templates/tasks/logout.html
{% extends "tasks/base.html" %}

{% block title %}Logout{% endblock %}

{% block content %}
  <h1>You've sucessfully logged out! :)</h1>>
  <a href="{% url 'main' %}">Click here to go back to the main page</a>
{% endblock %}

tasks/templates/tasks/main.html
{% extends 'tasks/base.html' %}

{% block content %}
<p>
<table class="table">
    <thead>
        <tr>
            <th>Task Number</th>
            <th>Task Name</th>
            <th>Notes</th>
            <th>Actions</th>
            <th><a href="{% url 'task_add' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a></th>
            <th><a href="{% url 'create_user' %}" class="top-menu">add user</span></a></th>
        </tr>
    </thead>
    <tbody>
        {% for task in tasks %}
        <tr>
            <th scope="row">{{task.pk}}</th>
            <td>{{task.title}}</td>
            <td>{{task.text}}</td>
            <td>
                <a class="btn btn-danger" type="submit" href="{% url 'task_delete' pk=task.pk %}">Delete</a>
                {% if task.title %}
                    This task has been completed :)
                {% else %}
                <a class="btn btn-primary" type="submit" href="{% url 'task_complete' pk=task.pk %}">Complete</a>
                {% endif %}
                <a class="btn btn-default" href="{% url 'task_edit' pk=task.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
            </td>
        </tr>
        {%endfor%}
    </tbody>
</table>

{% endblock %}